version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: niceusername
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: niceusername
          POSTGRES_DB: sport_news
          POSTGRES_PASSWORD: "very-strong-password"
    steps:
      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
