:schedule:
  UpdateViews:
    every: 1h
    class: UpdateViews
    enabled: true
  UpdateComments:
    every: 1h
    class: UpdateComments
    enabled: true
  UpdateSurveysStatus:
    every: 1d
    class: UpdateSurveysStatus
    enabled: true
